# Generated by Django 2.2.28 on 2023-11-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='photo',
            field=models.CharField(max_length=2000),
        ),
    ]
