# Generated by Django 2.2.28 on 2023-11-14 23:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id_lieu', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('disponibilite', models.CharField(choices=[('Libre', 'Libre'), ('Occupé', 'Occupé')], max_length=100)),
                ('photo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personnage',
            fields=[
                ('id_personnage', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('pseudonyme', models.CharField(max_length=50)),
                ('orientation', models.CharField(choices=[('Super-Héros', 'Super-héros'), ('Super-Vilain', 'Super-vilain')], max_length=100)),
                ('force_de_combat', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('etat', models.CharField(choices=[('Fatigué', 'Fatigué'), ('Reposé', 'Reposé'), ('Colérique', 'Colérique'), ('Heureux', 'Heureux')], max_length=100)),
                ('origineStory', models.TextField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=200)),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Lieu')),
            ],
        ),
    ]
